[package]
name = "koala"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.93"
eframe = "0.29"
egui = "0.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"

[[bin]]
name = "koala"
path = "bin/koala.rs"

[[bin]]
name = "koala_gui"
path = "bin/koala_gui.rs"
