[package]
name = "koala"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
anyhow = "1.0.93"
strum = "0.26"
strum_macros = "0.26"

[[bin]]
name = "koala_cli"
path = "bin/koala_cli.rs"

[[bin]]
name = "json_dump"
path = "bin/json_dump.rs"
