[package]
name = "koala-common"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Common utilities for the Koala browser"

[dependencies]
reqwest.workspace = true

[lints]
workspace = true
